% Copyright 2012 Sriram Radhakrishnan, Varun Sampath, Shilpa Sarode
% 
% This file is part of PVS.
% 
% PVS is free software: you can redistribute it and/or modify it under the
% terms of the GNU General Public License as published by the Free Software
% Foundation, either version 3 of the License, or (at your option) any later
% version.
% 
% PVS is distributed in the hope that it will be useful, but WITHOUT ANY
% WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
% PARTICULAR PURPOSE.  See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License along
% with PVS.  If not, see <http://www.gnu.org/licenses/>.

bpm1 = uicontrol ('Style', 'pushbutton',...
                   'String', 'BMP',...
                   'Position', [400, 100, 100, 50],...
                   'ForegroundColor', [0,0,0],... & Sets font color
                   'BackgroundColor', [0.5,0.5,0.5],... & Sets back color
                   'Callback', @setmap);
       
               
bpm2 = uicontrol ('Style', 'pushbutton',...
                   'String', 'BMP',...
                   'Position', [400, 175, 100, 50],...
                   'Callback', @setmap);             

bpm3 = uicontrol ('Style', 'pushbutton',...
                   'String', 'BMP',...
                   'Position', [400, 250, 100, 50],...
                   'Callback', @setmap);
               
bpm4 = uicontrol ('Style', 'pushbutton',...
                   'String', 'BMP',...
                   'Position', [400, 325, 100, 50],...
                   'Callback', @setmap);
