// -------------------------------------------------------------
// 
// File Name: hdlsrc\test_simple_gen.v
// Created: 2011-11-29 18:11:32
// 
// Generated by MATLAB 7.12 and Simulink HDL Coder 2.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Active                        ce_out        1
// State                         ce_out        1
// NdSt                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: test_simple_gen
// Source Path: test_simple_gen
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module test_simple_gen
          (
           clk,
           reset,
           clk_enable,
           ce_out,
           Active,
           State,
           NdSt
          );


  input   clk;
  input   reset;
  input   clk_enable;
  output  ce_out;
  output  Active;
  output  [7:0] State;  // uint8
  output  [7:0] NdSt;  // uint8


  wire TmpGroundAtNA_simpleInport1_out1;
  wire NA_simple_out1;
  wire [7:0] state_1;  // uint8
  wire [7:0] NA_simple_out3;  // uint8


  assign TmpGroundAtNA_simpleInport1_out1 = 1'b0;



  NA_simple   u_NA_simple   (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .inActive(TmpGroundAtNA_simpleInport1_out1),
                             .Active(NA_simple_out1),
                             .State(state_1),  // uint8
                             .NdSt(NA_simple_out3)  // uint8
                             );

  assign Active = NA_simple_out1;

  assign State = state_1;

  assign NdSt = NA_simple_out3;

  assign ce_out = clk_enable;

endmodule  // test_simple_gen

